#spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
#spring.main.allow-bean-definition-overriding=true

# debug MongoDB
#logging.level.org.springframework.data.mongodb.core=DEBUG
#logging.level.org.mongodb.driver=DEBUG


# Porta da aplicação
server.port=8080

# Configuração do banco H2
spring.datasource.url=jdbc:h2:mem:crudmongo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# JPA (para persistência)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Console do H2 habilitado
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging SQL